##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Terraform Project Deploy
on:
  workflow_dispatch:
  create:

  push:
    tags:
      - v*
    branches:
      - develop
      - support/**
      - release/**
    paths-ignore:
      - .github/workflows/**
      - modules/**

concurrency:
  group: plan-deploy-${{ github.repository }}
  cancel-in-progress: false

jobs:
  prevalidate:
    if: ${{ startsWith(github.ref,'refs/heads/release/') || startsWith(github.ref,'refs/heads/develop') || startsWith(github.ref,'refs/heads/support/') || startsWith(github.ref,'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      # Get the owner repo
      - name: Get owner
        id: getowner
        run: |
          repo_owner=`echo "$GITHUB_REPOSITORY" | cut -f 1 -d "/"`
          repo_name=`echo "$GITHUB_REPOSITORY" | cut -f 2 -d "/"`
          echo "owner=$repo_owner" >> $GITHUB_OUTPUT
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT

  deploy:
    needs:
      - prevalidate
    runs-on: ubuntu-latest
    steps:
      # Get the owner repo
      - name: Get owner
        id: getowner
        run: |
          repo_owner=`echo "$GITHUB_REPOSITORY" | cut -f 1 -d "/"`
          repo_name=`echo "$GITHUB_REPOSITORY" | cut -f 2 -d "/"`
          echo "owner=$repo_owner" >> $GITHUB_OUTPUT
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3

      # Get source of Configuration parameters (sensitive information)
      - name: Get Configuration source
        id: config_source
        uses: mikefarah/yq@master
        with:
          cmd: yq '.terraform.parameters.source' ./cloudopsworks-ci.yaml

      # Get Terraform SSM Parameter List
      - name: Get Terraform SSM Parameter List
        id: terraform_init_ssm
        if: steps.config_source.outputs.result == 'aws-ssm'
        uses: mikefarah/yq@master
        with:
          cmd: yq '.terraform.aws-ssm.paths.init' ./cloudopsworks-ci.yaml

      - name: Get region from terraform.tfvars
        id: aws_region
        if: steps.config_source.outputs.result == 'aws-ssm' || steps.config_source.outputs.result == 's3'
        uses: mikefarah/yq@master
        with:
          cmd: yq '.terraform.aws-ssm.region' ./cloudopsworks-ci.yaml

      - name: Get the deployments configuration
        id: deploy_conf
        uses: mikefarah/yq@master
        with:
          cmd: yq -o=json -I=0 '.cd.deployments' cloudopsworks-ci.yaml

      - name: Download TF init file from SSM
        id: tf_backend
        if: steps.config_source.outputs.result == 'aws-ssm'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ steps.aws_region.outputs.result }}
        run: |
          ssm_param="${{ steps.terraform_init_ssm.outputs.result }}"
          mkdir .deploy
          aws ssm get-parameters --names $ssm_param --query "Parameters[0].Value" --output text > .deploy/remote.tfbackend
          
          echo "config=.deploy/remote.tfbackend" >> $GITHUB_OUTPUT

      - name: Terraform Init With Remote Backend
        id: init_remote
        if: steps.config_source.outputs.result != 'none'
        run: terraform init -input=false -backend-config=${{ steps.tf_backend.outputs.config }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Terraform Init
        id: init
        if: steps.config_source.outputs.result == 'none'
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

      # Set the appropriate workspace from what is configured from the deploy_conf step
      # Result is stored as JSON with the format found on the cd.deployments section on cloudopsworks-ci.yaml
      - name: Set the appropriate workspace
        id: workspace
        uses: actions/github-script@v6
        with:
          script: |
            const deployments = JSON.parse('${{ steps.deploy_conf.outputs.result }}');
            const branch = '${{ github.ref_name }}';
            
            var tfWorkspace;
            var tfPrefix;
            var isRelease = false;
            var isPreRelease = false;
            var isEnabled = true;
            if ( branch.startsWith('support') ) {
              const oneMatch = deployments.support.find( ({ match }) => branch.match(new RegExp('support/'+match,'g')) );
              tfWorkspace = oneMatch.env;
              tfPrefix = oneMatch.terraformPrefix;
            } else if ( branch.startsWith('release') ) {
              isEnabled = (deployments.test['enabled'] == null ? true : (deployments.test['enabled'] === 'true'));
              tfWorkspace = deployments.test.env;
              tfPrefix = deployments.test.terraformPrefix;
            } else if ( branch === 'develop' ) {
              isEnabled = (deployments.develop['enabled'] == null ? true : (deployments.develop['enabled'] === 'true'));
              tfWorkspace = deployments.develop.env;
              tfPrefix = deployments.develop.terraformPrefix;
            } else {
              // This semver structure is obtained as per specification https://semver.org/ & https://regex101.com/r/vkijKf/1/
              semver = branch.match(/^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?/);
              if ( semver != null ) {
                const pre = semver['groups']['prerelease'];
                const buildmeta = semver['groups']['buildmetadata'];
                // buildmeta format is deploy-XXXX.yyy.zzz
                // the metasuffix should be the deploy- prefix
                if ( pre != null && buildmeta != null) {
                  const metasuffix = buildmeta.match(/deploy-(?<data>.*)/);
                  isEnabled = (deployments.prerelease['enabled'] == null ? true : (deployments.prerelease['enabled'] === 'true'));
                  isPreRelease = true;
                  tfWorkspace = deployments.prerelease.targets[metasuffix.groups.data].env;
                  tfPrefix = deployments.prerelease.targets[metasuffix.groups.data].terraformPrefix;
                } else if ( pre != null ) {
                  isEnabled = (deployments.prerelease['enabled'] == null ? true : (deployments.prerelease['enabled'] === 'true'));
                  // Regular expression to match following semver pattern: v1.0.2-alpha.10-uoiretu834u
                  isPreRelease = true;
                  tfWorkspace = deployments.prerelease.env;
                  tfPrefix = deployments.prerelease.terraformPrefix;                
                } else if ( buildmeta != null ) {
                  const metasuffix = buildmeta.match(/deploy-(?<data>.*)/);
                  isRelease = true;
                  tfWorkspace = deployments.release.targets[metasuffix.groups.data].env;
                  tfPrefix = deployments.release.targets[metasuffix.groups.data].terraformPrefix;                  
                } else {
                  isRelease = true;
                  tfWorkspace = deployments.release.env;
                  tfPrefix = deployments.release.terraformPrefix;
                }
              } else {
                core.setFailed('Branch not supported');
              }
            }            
            
            const outputV = { 
              workspace: tfWorkspace, 
              prefix: tfPrefix, 
              isPreRelease: isPreRelease, 
              isRelease: isRelease,
              isEnabled: isEnabled
            }; 
            core.setOutput('workspace', tfWorkspace);
            core.setOutput('prefix', tfPrefix);
            core.setOutput('isRelease', isRelease);
            core.setOutput('isPreRelease', isPreRelease);
            core.setOutput('isEnabled', isEnabled);
            
            return outputV;

      - name: Create Plan Directory
        run: mkdir -p ./.plans

      - name: Terraform Workspace Check Existence and Selection
        id: workspace_check
        run: |
          terraform workspace select ${{ steps.workspace.outputs.workspace }}
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Terraform Workspace Create
        if: steps.workspace_check.outcome == 'failure'
        run: |
          terraform workspace new ${{ steps.workspace.outputs.workspace }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Terraform Plan
        id: plan
        if: ${{ steps.workspace.outputs.isEnabled == 'true' }}
        run: |
          terraform plan -var-file tfvars/${{ steps.workspace.outputs.prefix }}.terraform.tfvars  -input=false -no-color -out ./.plans/plan.out
        continue-on-error: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
#          HELM_CREDS_USER: ${{ secrets.HELM_CREDENTIAL_USER }}
#          HELM_CREDS_PASSWORD: ${{ secrets.HELM_CREDENTIAL_PASSWORD }}
          HELM_EXPERIMENTAL_OCI: "1"
          GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Terraform Apply
        id: apply
        if: ${{ steps.workspace.outputs.isEnabled == 'true' }}
        run: |
          terraform apply -no-color ./.plans/plan.out
        continue-on-error: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
#          HELM_CREDS_USER: ${{ secrets.AZURE_SERVICE_ID }}
#          HELM_CREDS_PASSWORD: ${{ secrets.AZURE_SERVICE_SECRET }}
          HELM_EXPERIMENTAL_OCI: "1"
          GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

      # Create a VERSION file to use through the build
      - name: Set Version File
        if: ${{ ( steps.workspace.outputs.isRelease == 'true' || steps.workspace.outputs.isPreRelease == 'true' ) && steps.workspace.outputs.isEnabled == 'true' }}
        env:
          NEXT_VERSION: "${{ github.ref_name }}"
        run: |
          echo -n "$NEXT_VERSION" > VERSION

      # Output Changelog from previous tag
      - name: Changelog
        if: ${{ ( steps.workspace.outputs.isRelease == 'true' || steps.workspace.outputs.isPreRelease == 'true' ) && steps.workspace.outputs.isEnabled == 'true'  }}
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          output: CHANGELOG.md

      # Create GitHub Release
      - name: GitHub Release
        if: ${{ ( steps.workspace.outputs.isRelease == 'true' || steps.workspace.outputs.isPreRelease == 'true' ) && steps.workspace.outputs.isEnabled == 'true'  }}
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          name: "Release ${{ github.ref_name }}"
          body_path: CHANGELOG.md
          prerelease: ${{ steps.workspace.outputs.isPreRelease }}

#      # Push the changes to Git TAG before deploying anything
#      - name: Release Version
#        if: github.ref == 'master'
#        env:
#          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#        run: |
#          VERSION=$(cat VERSION)
#          git config --global user.name "${{ vars.BOT_USER }}"
#          git config --global user.email "${{ vars.BOT_EMAIL }}"
#          git tag -fa v$VERSION -m "Environment Release v$VERSION"
#          git push origin v$VERSION
